spring:
  datasource:
    username: "USERNAME"
    password: "PASSWORD"
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: "INTROSPECTION_URI"
          client-id: "CLIENT_ID"
          client-secret: "CLIENT_SECRET"

custom:
  amazon-s3:
    endPoint: "END_POINT"
    regionName: "REGION_NAME"
    accessKey: "ACCESS_KEY"
    secretKey: "SECRET_KEY"
    bucketName: "BUCKET_NAME"
  cdn:
    endPoint: "END_POINT"