spring:
  profiles:
    active: local
    include: secrets
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:12000/posts_dev
    username: "USERNAME" # secret
    password: "PASSWORD" # secret
  jpa:
    properties:
      hibernate.default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true # 이 설정을 하지 않을 경우 sql init가 먼저 실행됨
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: "INTROSPECTION_URI" # secret
          client-id: "CLIENT_ID" # secret
          client-secret: "CLIENT_SECRET" # secret
  sql:
    init:
      mode: always

decorator:
  datasource:
    p6spy:
      enable-logging: true

custom:
  amazon-s3:
    endPoint: "END_POINT" # secret
    regionName: "REGION_NAME" # secret
    accessKey: "ACCESS_KEY" # secret
    secretKey: "SECRET_KEY" # secret
    bucketName: "BUCKET_NAME" # secret
  cdn:
    endPoint: "END_POINT" # secret